version: '3.8'

services:
  # Serviço 1: Seu script Go de ETL (Comentado por enquanto)
  # etl-service:
  #   build: ...

  # SERVIÇO 2: O Apache Superset
  superset:
    image: txagou/superset-pipeline:latest
    platform: linux/amd64
    container_name: superset_dashboard
    ports:
      - "8088:8088"
    environment:
      SUPERSET_SECRET_KEY: "seminario_big_data_2026"
    depends_on:
      - db-postgres

  # SERVIÇO 3: O Banco de Dados PostgreSQL
  db-postgres:
    image: postgres:15
    platform: linux/amd64
    container_name: pokemon_db
    environment:
      POSTGRES_USER: joao_admin
      POSTGRES_PASSWORD: minhasenha
      POSTGRES_DB: pokemon_dw
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

# Mapeamento do volume do banco
volumes:
  postgres_data: